name = "RegularizedCovarianceMatrices"
uuid = "5bfb50f7-5e0c-48f2-b6cf-e6e905952022"
authors = ["raphasampaio", "joaquimg", "mvpoggi", "vidalt"]
version = "0.1.4"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Aqua = "0.6, 0.7, 0.8"
LinearAlgebra = "1.6 - 1.11"
Random = "1.6 - 1.11"
Statistics = "1"
StatsBase = "0.33, 0.34"
Test = "1.6 - 1.11"
TimerOutputs = "0.5"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["Aqua", "Random", "StatsBase", "Test", "TimerOutputs"]
